-- Generated by AllQuest/tools/extract_chains.py
-- Linear next-in-chain coverage. Rename / branch in Overlay.lua.
-- This file is a sample of extractor output from tools/quests_sample.json.
local AQ = AllQuest
if not AQ or not AQ.Data then return end

AQ.Data:AddCategory({
    id = 1001,
    expansion = 0,
    name = "Elwynn Forest",
})

AQ.Data:AddChain({
    id = 90001,
    category = 1001,
    expansion = 0,
    name = "A Threat Within",
    restrictions = { faction = "Alliance" },
    prerequisites = { { type = "level", min = 1 } },
    nodes = {
        { id = 1, type = "quest", questID = 783, next = { 2 } },
        { id = 2, type = "quest", questID = 5261, next = { 3 } },
        { id = 3, type = "quest", questID = 33, next = { 4 } },
        { id = 4, type = "quest", questID = 7, next = {} },
    },
})
