#!/usr/bin/env python3
"""Build WowGPS destination database for offline maintenance.

Run from the addon root:
  python tools/build_destinations.py --flavor retail

Output is written to Data/Destinations_generated.lua (not loaded at runtime yet).
Seed data in Data/Destinations_seed.lua ships with the addon for development.
"""

from __future__ import annotations

import argparse
from pathlib import Path

ADDON_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ADDON_ROOT / "Data" / "Destinations_generated.lua"


def main() -> None:
    parser = argparse.ArgumentParser(description="Build WowGPS destination Lua data.")
    parser.add_argument("--flavor", default="retail", choices=["retail", "vanilla", "tbc", "wrath", "cata", "mists"])
    args = parser.parse_args()

    header = f"""-- AUTO-GENERATED by tools/build_destinations.py ({args.flavor})
-- Do not edit by hand.

local _, ns = ...
ns.DestinationsGenerated = ns.DestinationsGenerated or {{}}
ns.DestinationsGenerated["{args.flavor}"] = {{
}}
"""
    OUTPUT.write_text(header, encoding="utf-8")
    print(f"Wrote placeholder: {OUTPUT}")


if __name__ == "__main__":
    main()
